services:
  db:
    image: mysql:5.7
    container_name: thrive_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: healthcare_chatbot
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thrive_network
    ports:
      - "8001:3306"
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  # Specify the Dockerfile for backend
    container_name: thrive_backend
    depends_on:
      - db  # Wait for MySQL container to start first
    networks:
      - thrive_network
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile  # Specify the Dockerfile for frontend
    container_name: thrive_chatbot
    networks:
      - thrive_network
    ports:
      - "5173:5173" 
    restart: always

networks:
  thrive_network:
    driver: bridge
